# pGlyco Auto Combine Configuration

# Input/Output paths
paths:
  dataset_dir: "Dataset"
  results_dir: "Results"
  output_file: "integrated.csv"

# Data processing parameters
processing:
  required_columns:
    - "Peptide"
    - "GlycanComposition"
    - "IsotopeArea"
    - "Proteins"

  # Quality control filters
  qc_filters:
    min_isotope_area: 0  # Minimum IsotopeArea threshold

# Annotation parameters
annotation:
  sialylation_marker: "A"  # Presence of A indicates sialylation
  fucosylation_marker: "F"  # Presence of F indicates fucosylation

# Analysis parameters
analysis:
  pca:
    n_components: 2
    log_transform: true  # Log transform intensity values

  # STANDARDIZED DATA PREPARATION SETTINGS (CRITICAL for reproducibility)
  # These parameters ensure CONSISTENT filtering and processing across ALL visualizations
  detection_filter:
    min_detection_pct: 0.30  # Minimum 30% detection in at least one group (Cancer OR Normal)
    min_samples: 5           # Minimum 5 detected samples for statistical tests

  missing_data_handling:
    method: 'skipna'  # 'skipna' (RECOMMENDED - exclude missing from mean) or 'replace_zero' (legacy - include as zero)
    # SCIENTIFIC NOTE: 'skipna' is correct for Missing Not At Random (MNAR) data in proteomics
    # Using 'replace_zero' will underestimate intensities for low-detection glycopeptides

  statistical_tests:
    alpha: 0.05  # Significance threshold
    fdr_correction: true  # Apply Benjamini-Hochberg FDR correction
    method: 'mannwhitneyu'  # 'mannwhitneyu' (non-parametric) or 'ttest' (parametric)

    # Phase 1.2: S0-adjusted t-test parameters (SAM method from AlphaPepStats)
    # Prevents inflation of t-statistics from small variances
    s0_parameter: 0.05  # Minimum trusted standard deviation (default: 0.05)
    use_s0_adjusted: true  # Use S0-adjusted p-values (RECOMMENDED for publication)
    # SCIENTIFIC NOTE: S0-adjusted t-test is more stable than regular t-test
    # Especially important for features with small variances
    # Inspired by SAM (Significance Analysis of Microarrays)

  # Phase 11.1: Differential expression thresholds
  # These thresholds define what constitutes "significant" differential expression
  differential_expression:
    log2fc_strict: 2.0  # 4-fold change threshold (highly differential features)
                        # Used for: Volcano plot, significant feature selection
    log2fc_moderate: 1.0  # 2-fold change threshold (moderately differential)
                          # Used for: Sankey diagrams, general filtering
    fdr_threshold: 0.05  # False discovery rate threshold (5%)
                         # Controls for multiple testing
    vip_threshold: 1.0  # VIP score threshold for feature importance
                        # Features with VIP > 1.0 considered important

  # Phase 11.1: Effect size thresholds (Cohen's d)
  # Measures biological significance beyond statistical significance
  effect_sizes:
    cohens_d_small: 0.2  # Small effect (detectable but minor)
    cohens_d_medium: 0.5  # Medium effect (moderate biological importance)
    cohens_d_large: 0.8  # Large effect (strong biological significance)
                         # Biomarker candidates should have large effects

  # Phase 11.1: Biomarker validation criteria
  # Stringent criteria for identifying reliable biomarkers
  biomarker_criteria:
    stability_threshold: 0.8  # 80% bootstrap stability required
                              # Feature must be selected in 80% of bootstrap iterations
    min_detection_rate: 0.6  # 60% detection across samples required
                             # Feature must be detected in majority of samples
    min_effect_size: 0.8  # Minimum Cohen's d for biomarker consideration
                          # Must have large effect size to be considered

# Visualization parameters
visualization:
  figsize:
    pca: [10, 8]
    boxplot: [12, 6]
    heatmap: [14, 10]

  dpi: 300

  colors:
    # Legacy colors (for backward compatibility)
    Non: "#CCCCCC"
    Sialylated: "#E74C3C"
    Fucosylated: "#3498DB"
    Both: "#9B59B6"

    # Primary classification colors
    Truncated: "#CCCCCC"
    "High Mannose": "#2ECC71"
    ComplexHybrid: "#3498DB"
    Outlier: "#E67E22"

    # Secondary classification colors
    "Complex/Hybrid": "#3498DB"
    Fucosylated_secondary: "#E74C3C"
    Sialylated_secondary: "#9B59B6"
    Sialofucosylated: "#F39C12"

  # Glycopeptide comparison heatmap settings (NEW)
  glycopeptide_comparison:
    enabled: true
    max_peptides: 20  # Top N unique peptides (from top glycopeptides by VIP score)
    max_glycans_per_type: 15  # Top N glycans per type
    figsize: [24, 16]  # Width x Height in inches

    # Glycan type category colors (for dot heatmap)
    glycan_type_colors:
      HM: "#00CC00"      # High-mannose (Green)
      F: "#FF0000"       # Fucosylated (Red)
      S: "#FF69B4"       # Sialylated (Pink)
      SF: "#FFA500"      # Sialofucosylated (Orange)
      "C/H": "#0000FF"   # Complex/Hybrid (Blue)

# Phase 11.1: Pipeline execution settings
# Controls progress reporting, timing, and data quality visibility
execution:
  # Progress reporting configuration
  progress_reporting:
    enabled: true  # Enable progress bars and status updates
    statistical_tests: true  # Show progress for statistical tests
    visualizations: true  # Show progress for plot generation
    data_loading: true  # Show progress for CSV loading

  # Execution timing configuration
  timing:
    enabled: true  # Log execution time for each pipeline stage
    detailed: false  # Log timing for individual operations (very verbose)

  # Data quality reporting configuration
  data_quality:
    report_after_loading: true  # Log quality summary after data loading
    report_after_filtering: true  # Log quality summary after filtering
    report_after_preprocessing: true  # Log quality summary after preprocessing
